name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Go fmt
        run: |
          git fetch origin main
          files=$(git diff --name-only --diff-filter=ACM origin/main | grep '\.go$' || true)
          if [ -z "$files" ]; then
            echo "No Go files changed"
            exit 0
          fi
          unformatted=$(gofmt -l $files)
          if [ -n "$unformatted" ]; then
            echo "The following files are not formatted:"
            echo "$unformatted"
            exit 1
          fi
      - name: Go lint
        run: |
          git fetch origin main
          files=$(git diff --name-only --diff-filter=ACM origin/main | grep '\.go$' || true)
          if [ -n "$files" ]; then
            go install golang.org/x/lint/golint@latest
            golint -set_exit_status $files
          fi
      - name: Go vet
        run: go vet ./...
      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
      - name: Go test
        run: go test -coverprofile=coverage.out ./...
      - name: Go test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: coverage.out
